spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
naver:
  client-id: KsCtXhM1Feo7P0K24Oka
  client-secret: e7m7DCN1vn
